import sqlite3

conn = sqlite3.connect('config.db')
print("Opened database successfully");

# create cursor object
cur = conn.cursor()
# check if table exists
listOfTables = cur.execute(
  """SELECT name FROM sqlite_master WHERE type='table'
  AND name='SENSOR_CONFIG'; """).fetchall()

if listOfTables == []:
    cur.execute("""CREATE TABLE SENSOR_CONFIG (ID INT PRIMARY KEY NOT NULL, GROUPID INT  NOT NULL, LAT REAL NULL, LON REAL NULL, LOCATION VARCHAR NULL, CONTROLID INT NOT NULL, ACTUATORSTAT INT NULL);""")
    print("Table created successfully")

    # Sensor Group 1
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_1', 1, 12.9767936, 77.590082, 'Bangalore', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_2', 1, 12.9767936, 77.590082, 'Bangalore', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_3', 1, 12.9767936, 77.590082, 'Bangalore', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_4', 1, 12.9767936, 77.590082, 'Bangalore', 0, 0);""")

    # Sensor Group 2
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_5', 2, 51.5073219, -0.1276474, 'London', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_6', 2, 51.5073219, -0.1276474, 'London', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_7', 2, 51.5073219, -0.1276474, 'London', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_8', 2, 51.5073219, -0.1276474, 'London', 0, 0);""")

    # Sensor Group 3
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_9', 3, 0.3177137, 32.5813539, 'Kampala', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_10', 3, 0.3177137, 32.5813539, 'Kampala', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_11', 3, 0.3177137, 32.5813539, 'Kampala', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_12', 3, 0.3177137, 32.5813539, 'Kampala', 0, 0);""")

    # Sensor Group 4
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_13', 4, 35.6828387, 139.7594549, 'Tokyo', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_14', 4, 35.6828387, 139.7594549, 'Tokyo', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_15', 4, 35.6828387, 139.7594549, 'Tokyo', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_16', 4, 35.6828387, 139.7594549, 'Tokyo', 0, 0);""")

    # Sensor Group 5
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_17', 5, 29.758938, -95.3676974, 'Houston', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_18', 5, 29.758938, -95.3676974, 'Houston', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_19', 5, 29.758938, -95.3676974, 'Houston', 0, 0);""")
    cur.execute("""INSERT INTO SENSOR_CONFIG (ID,GROUPID,LAT,LON,LOCATION,CONTROLID,ACTUATORSTAT) VALUES ('SOIL_SENS_20', 5, 29.758938, -95.3676974, 'Houston', 0, 0);""")

    conn.commit()
    print("Records created successfully");
    conn.close()

else:

    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_1';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_2';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_3';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_4';""")

    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_5';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_6';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_7';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_8';""")

    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_9';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_10';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_11';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_12';""")

    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_13';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_14';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_15';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_16';""")

    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_17';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_18';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_19';""")
    cur.execute("""UPDATE SENSOR_CONFIG SET CONTROLID=0,ACTUATORSTAT=0 WHERE ID='SOIL_SENS_20';""")

    conn.commit()
    print("Records updated successfully");

    print("Table found!")
    print('Print SENSOR_CONFIG data:')
    SenorConfig = cur.execute("""SELECT * FROM SENSOR_CONFIG ; """).fetchall()
    print(SenorConfig)

    conn.close()
